In [1]:
import pandas as pd
titanic_data_frame=pd.read_csv('titanic.csv')
titanic_data_frame.dropna(how='any')
survived=titanic_data_frame[titanic_data_frame['Survived']==True]
survived_precent=(len(survived)/len(titanic_data_frame))*100
survived_precent

38.38383838383838

In [3]:
max_price = titanic_data_frame['Fare'].max()
min_price= titanic_data_frame['Fare'].min()
print(max_price,min_price)

512.3292 0.0

In [5]:
middle_age = titanic_data_frame['Age'].mean()
middle_age

29.69911764705882

In [8]:
junior_survived=len(titanic_data_frame[(titanic_data_frame['Survived']==True) & (titanic_data_frame['Age']<18)]) / len(titanic_data_frame[titanic_data_frame['Age']<18])*100
middle_survived=len(titanic_data_frame[(titanic_data_frame['Survived']==True) & (titanic_data_frame['Age']>=18) & (titanic_data_frame['Age']<50) ])/len(titanic_data_frame[(titanic_data_frame['Age']>=18) & (titanic_data_frame['Age']<50)])*100
old_survived=len(titanic_data_frame[(titanic_data_frame['Survived']==True) & (titanic_data_frame['Age']>=50)])/len(titanic_data_frame[titanic_data_frame['Age']>=50])*100
print(junior_survived,middle_survived,old_survived)

53.98230088495575 38.33017077798861 36.486486486486484

In [10]:
titanic_data_frame['Fare'].sum()

28693.9493

In [16]:
def get_first_variant(df):
    additionally_data=[]
    for i in df.columns:
        additionally_data.append(i)
    return pd.DataFrame({'Year':[int(additionally_data[0]),*df['1990']],'Region':[str(additionally_data[1]),*df['Адыгея']],'Population':[float(additionally_data[2]),*df['434788.0']]})
def get_second_variant(df):
    years=[str(i) for i in df['Year'].unique()]
    regions=[str(i) for i in df['Region'].unique()]
    pre_data_frame={}
    pre_data_frame['Region']=[]
    for k in years:
        pre_data_frame[str(k)]=[]
    for i in regions:
        pre_data_frame['Region'].append(i)
        for j in years:
            try:
                pre_data_frame[str(j)].append(float(df[(df['Region']==i) & (df['Year']==int(j))]['Population']))
            except:
                pre_data_frame[str(j)].append(float(np.nan))
    return pd.DataFrame(pre_data_frame)
ugly_data_frame=pd.read_csv('russian_population_by_years.csv')
ugly_data_frame.dtypes
get_first_variant(ugly_data_frame).to_csv('russian_population_by_years_first.csv')
first_df=pd.read_csv('russian_population_by_years_first.csv')
get_second_variant(first_df).to_csv('russian_population_by_years_second.csv')
russian_population_by_years_second=pd.read_csv('russian_population_by_years_second.csv')
russian_population_by_years_second

,Unnamed: 0,Region,1990,1991,1992,1993,1994,1995,1996,1997,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,0,Адыгея,434788.0,436598.0,441280.0,446191.0,448480.0,449864.0,450358.0,450075.0,...,439760.0,439935.0,442451.0,444403.0,446406.0,449171.0,451480.0,453366.0,453376.0,454744.0
1,1,Алтайский край,2640419.0,2653818.0,2664886.0,2680334.0,2684297.0,2694271.0,2688035.0,2676677.0,...,2430765.0,2417358.0,2407230.0,2398751.0,2390638.0,2384812.0,2376774.0,2365680.0,2350080.0,2332813.0
2,2,Амурская область,1055337.0,1054267.0,1048649.0,1029516.0,1018407.0,995012.0,986417.0,974942.0,...,834905.0,828660.0,821573.0,816910.0,811274.0,809873.0,805689.0,801752.0,798424.0,793194.0
3,3,Архангельская область,1523509.0,1517293.0,1504339.0,1489573.0,1471475.0,1453656.0,1432697.0,1412345.0,...,1195378.0,1182776.0,1171096.0,1159506.0,1148760.0,1139950.0,1130240.0,1121813.0,1111031.0,1100290.0
4,4,Астраханская область,997516.0,1001044.0,1003253.0,1004737.0,1006099.0,1014170.0,1019171.0,1020576.0,...,1011120.0,1009801.0,1014972.0,1013840.0,1016516.0,1021287.0,1018626.0,1018866.0,1017514.0,1014065.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,80,Чувашия,1337182.0,1339822.0,1344014.0,1347818.0,1345489.0,1345431.0,1343966.0,1341946.0,...,1255852.0,1250518.0,1247012.0,1243431.0,1239984.0,1238071.0,1236628.0,1235863.0,1231117.0,1223395.0
81,81,Чукотский автономный округ,162135.0,158056.0,147930.0,124351.0,111422.0,95769.0,84451.0,77917.0,...,51179.0,50346.0,50988.0,50780.0,50555.0,50540.0,50157.0,49822.0,49348.0,49663.0
82,82,Якутия,1111480.0,1118983.0,1100342.0,1079678.0,1064617.0,1037155.0,1020320.0,1010110.0,...,958338.0,958258.0,955859.0,955580.0,954803.0,956896.0,959689.0,962835.0,964330.0,967009.0
83,83,Ямало-Ненецкий автономный округ,489161.0,488577.0,477111.0,463790.0,467467.0,478033.0,487050.0,491900.0,...,524141.0,524925.0,536558.0,541612.0,539671.0,539985.0,534104.0,536049.0,538547.0,541479.0
84,84,Ярославская область,1472126.0,1473837.0,1469449.0,1464220.0,1456922.0,1452718.0,1446797.0,1437494.0,...,1280088.0,1271006.0,1271030.0,1271672.0,1271766.0,1271629.0,1271912.0,1270736.0,1265684.0,1259612.0